Repository serg-rsv/team-project-care-pets, pull requests merged in 2022-11, with the labels that each got.

#2 Niko #1
  frontend/src/App.js
  frontend/src/images/image.png
  frontend/src/scss/base/_common.scss
  frontend/src/scss/utils/_mixins.scss
  frontend/src/scss/utils/_variables.scss
Labels: enhancement

#8 Feat/auth close #7
  backend/config/.env.example
  backend/config/db.js
  backend/controllers/index.js
  backend/controllers/user/edit.js
  backend/controllers/user/index.js
  backend/controllers/user/login.js
  backend/controllers/user/logout.js
  backend/controllers/user/register.js
  backend/helpers/index.js
  backend/helpers/requestError.js
  backend/middleware/auth.js
  backend/middleware/errorHandler.js
  backend/middleware/index.js
  backend/models/User.js
  backend/models/index.js
  backend/routes/api/index.js
  backend/routes/api/users.js
  backend/server.js
  backend/validators/index.js
  backend/validators/isValidId.js
  backend/validators/schemaJoiValidator.js
  package-lock.json
  package.json
Labels: enhancement

#32 Test and fix some global styles reset
  frontend/src/scss/base/_common.scss
Labels: bug

#38 Niko #37
  backend/config/.env.example
  backend/controllers/pets/addPet.js
  backend/controllers/pets/deletePet.js
  backend/controllers/pets/getOwnerPets.js
  backend/controllers/pets/index.js
  backend/models/Notice.js
  backend/models/Pet.js
  backend/models/index.js
  backend/routes/api/index.js
  backend/routes/api/pets.js
  backend/server.js
  backend/validators/index.js
  backend/validators/isValidPetFields.js
  backend/validators/schemaJoiValidator.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  package-lock.json
Labels: backend

#41 done with /news routes #40
  backend/controllers/news/addNewsController.js
  backend/controllers/news/getNewsController.js
  backend/controllers/news/index.js
  backend/models/News.js
  backend/models/index.js
  backend/routes/api/index.js
  backend/routes/api/news.js
  backend/server.js
  frontend/src/components/PetPage/NoticesCategoriesList/NoticesCategoriesList.jsx
  frontend/src/components/PetPage/NoticesSearch/NoticesSearch.jsx
Labels: backend

#43 done with /services-sidebar #42
  backend/controllers/friends/addFriendController.js
  backend/controllers/friends/getAllFriendsController.js
  backend/controllers/friends/index.js
  backend/models/Friend.js
  backend/models/index.js
  backend/routes/api/friends.js
  backend/routes/api/index.js
  backend/server.js
  package-lock.json
  package.json
Labels: backend

#46 add cmments to pet
  backend/models/Pet.js
  backend/validators/isValidPetFields.js
  frontend/package-lock.json
  frontend/src/components/AuthNav/AuthNav.module.scss
  frontend/src/components/button/button.module.scss
  package-lock.json
Labels: backend

#73 fix bug with npm run dev, modify and deleating some config files
  .eslintignore
  .eslintrc.js
  frontend/package-lock.json
  frontend/src/redux/store.js
  frontend/src/redux/usersSlice.js
  package-lock.json
  package.json
Labels: bug, invalid

#74 fix userData closes #76
  frontend/src/components/LogOut/LogOut.module.scss
  frontend/src/components/PetsData/PetsData.jsx
  frontend/src/components/PetsData/PetsData.module.scss
  frontend/src/components/UserData/UserData.jsx
  frontend/src/components/UserData/UserData.module.scss
  frontend/src/components/UserView/UserView.module.scss
  frontend/src/components/UserView/index.js
  frontend/src/images/del-black.svg
  frontend/src/images/del-orange.svg
  frontend/src/images/delHover.png
  frontend/src/images/iconDel.png
  frontend/src/pages/UserPage/UserPage.jsx
Labels: bug

#80 fix getNewsListController
  backend/controllers/news/getNewsListController.js
Labels: invalid, backend

#90 Niko#69 Close #83 #89 #88
  backend/controllers/friends/getFriendsListController.js
  backend/controllers/news/getNewsListController.js
  backend/controllers/notices/getAll.js
  backend/controllers/notices/getByCategory.js
  backend/controllers/notices/getPersonalNotices.js
  backend/middleware/uploadMiddleware.js
  backend/services/friendsService.js
  backend/services/newsService.js
  backend/validators/isValidPetFields.js
  frontend/package-lock.json
Labels: backend

#92 fix deletePet middleware when photoId is empty
  backend/controllers/pets/deletePetController.js
  backend/middleware/cleanImgMiddleware.js
  backend/middleware/cleanUserAvatarMiddleware.js
  backend/middleware/uploadMiddleware.js
  backend/services/petsService.js
Labels: backend

#106 Niko Close #105
  backend/controllers/user/edit.js
  backend/controllers/user/getCurrentUser.js
  backend/middleware/uploadMiddleware.js
  backend/models/User.js
  backend/services/cloudinaryService.js
  frontend/src/App.js
  frontend/src/components/UserButton/UserButton.jsx
  frontend/src/components/UserButton/UserButton.module.scss
  frontend/src/components/UserButton/index.js
  frontend/src/components/UserData/UserData.jsx
  frontend/src/components/UserData/UserData.module.scss
  frontend/src/components/UserView/UserView.jsx
  frontend/src/components/button/index.js
  frontend/src/redux/services/authSlice.js
  frontend/src/redux/services/usersSlice.js
  package-lock.json
Labels: enhancement

#112 Close #111 Fix register and login
  backend/controllers/user/register.js
  frontend/package-lock.json
  frontend/src/components/LoginForm/LoginForm.jsx
  frontend/src/components/RegisterForm/RegisterForm.jsx
  frontend/src/redux/services/usersSlice.js
Labels: enhancement

#115 Set favorites closes #114
  frontend/src/components/LogOut/LogOut.jsx
  frontend/src/components/PetPage/NoticeCategoryItem/NoticeCategoryItem.jsx
  frontend/src/components/PetPage/NoticeCategoryItem/NoticeCategoryItem.module.scss
  frontend/src/components/PetPage/NoticesCategoriesList/NoticesCategoriesList.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/Favorite/Favorite.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/InGoodHands/InGoodHands.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/LostFound/LostFound.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/Own/Own.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/Sell/Sell.jsx
  frontend/src/helpers/markFavoriteNotice.js
  frontend/src/redux/services/.gitkeep
  frontend/src/redux/services/baseApi.js
  frontend/src/redux/services/noticesSlice.js
  frontend/src/redux/services/petsSlice.js
  frontend/src/redux/services/usersSlice.js
  frontend/src/redux/store.js
Labels: enhancement

#120 Niko Close #118 #119
  backend/controllers/notices/getById.js
  backend/middleware/uploadMiddleware.js
  backend/models/Notice.js
  frontend/src/App.js
  frontend/src/components/Button/Button.module.scss
  frontend/src/components/Modal/Modal.jsx
  frontend/src/components/Modal/Modal.module.scss
  frontend/src/components/ModalAddNotice/ModalAddNotice.jsx
  frontend/src/components/ModalAddNotice/modalAddNotice.module.scss
  frontend/src/components/ModalAddPet/ModalAddPet.jsx
  frontend/src/components/ModalAddPet/modalAddPet.module.scss
  frontend/src/components/PetPage/AddNoticeButton/AddNoticeButton.jsx
  frontend/src/components/PetPage/NoticeCategoryItem/NoticeCategoryItem.jsx
  frontend/src/components/PetPage/NoticeCategoryItem/NoticeCategoryItem.module.scss
  frontend/src/components/PetPage/NoticesSearch/NoticesSearch.jsx
  frontend/src/components/PetsData/PetsData.jsx
  frontend/src/components/PetsData/PetsData.module.scss
  frontend/src/components/RegisterForm/RegisterForm.jsx
  frontend/src/components/UserView/UserView.jsx
  frontend/src/components/UserView/UserView.module.scss
  frontend/src/helpers/formDataAppender.js
  frontend/src/helpers/urlGenerator.js
  frontend/src/redux/services/baseApi.js
  frontend/src/redux/services/noticesSlice.js
  frontend/src/redux/services/petsSlice.js
Labels: enhancement

#125 Made search by categories and refactor store Close #110
  frontend/src/components/Button/Button.jsx
  frontend/src/components/Button/Button.module.scss
  frontend/src/components/Navigation/Navigation.jsx
  frontend/src/components/PetPage/AddNoticeButton/AddNoticeButton.module.scss
  frontend/src/components/PetPage/NoticesCategoriesList/NoticesCategoriesList.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/Container/Container.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/Container/Container.module.scss
  frontend/src/components/PetPage/NoticesCategoriesNav/InGoodHands/InGoodHands.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/LostFound/LostFound.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/NoticesCategoriesNav.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/Sell/Sell.jsx
  frontend/src/components/PetPage/NoticesSearch/NoticesSearch.jsx
  frontend/src/components/Routes/PrivateRoute.jsx
  frontend/src/components/Routes/PublicRoute.jsx
  frontend/src/redux/noticesSlice.js
  frontend/src/redux/selectors.js
  frontend/src/redux/services/authSlice.js
  frontend/src/redux/services/noticesSlice.js
  frontend/src/redux/store.js
  frontend/src/scss/base/_common.scss
Labels: enhancement

#175 Close #136 #172 #140 #174
  frontend/src/components/AuthNav/AuthNav.jsx
  frontend/src/components/ModalAddPet/ModalAddPet.jsx
  frontend/src/components/Navigation/Navigation.jsx
  frontend/src/components/Navigation/Navigation.module.scss
  frontend/src/components/PetsData/PetsData.jsx
  frontend/src/components/RegisterForm/RegisterForm.jsx
  frontend/src/components/UserData/UserData.jsx
  frontend/src/components/UserNav/UserNav.jsx
Labels: bug, fixed

#180 fix toast Close #179
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/ModalAddPet/ModalAddPet.jsx
  frontend/src/components/PetPage/NoticeCategoryItem/NoticeCategoryItem.jsx
  frontend/src/helpers/toastOptions.js
  frontend/src/index.js
  package-lock.json
  package.json
Labels: bug, fixed

#186 Niko Close #179 #183
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/LogOut/LogOut.jsx
  frontend/src/components/LogOut/LogOut.module.scss
  frontend/src/components/Modal/Modal.module.scss
  frontend/src/components/Navigation/Navigation.jsx
  frontend/src/components/PetPage/ModalNotice/ModalNotice.module.scss
  frontend/src/components/PetPage/NoticeCategoryItem/NoticeCategoryItem.jsx
  frontend/src/components/PetPage/NoticeCategoryItem/NoticeCategoryItem.module.scss
  frontend/src/components/PetPage/NoticesCategoriesList/NoticesCategoriesList.jsx
  frontend/src/components/PetPage/NoticesCategoriesList/NoticesCategoriesList.module.scss
  frontend/src/components/PetPage/NoticesCategoriesNav/Favorite/Favorite.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/InGoodHands/InGoodHands.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/LostFound/LostFound.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/Own/Own.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/Sell/Sell.jsx
  frontend/src/images/addNoticeModal.svg
  frontend/src/images/cat.svg
  frontend/src/images/heart.svg
  frontend/src/redux/services/baseApi.js
  frontend/src/scss/utils/_mixins.scss
Labels: bug, enhancement, fixed

#189 Niko Close #187 #188
  .gitignore
  frontend/src/App.js
  frontend/src/components/PetPage/NoticesCategoriesList/NoticesCategoriesList.jsx
  frontend/src/components/PetPage/NoticesCategoriesList/NoticesCategoriesList.module.scss
  frontend/src/components/PetsData/PetsData.jsx
  frontend/src/components/PetsData/PetsData.module.scss
  frontend/src/images/pows.svg
  frontend/src/images/wonderW.svg
  frontend/src/pages/NotFound/NotFound.jsx
  frontend/src/pages/NotFound/NotFound.module.scss
  frontend/src/pages/NotFound/index.js
Labels: enhancement, fixed

#194 fix loadmore Close #193
  frontend/src/components/PetPage/NoticesCategoriesNav/Favorite/Favorite.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/InGoodHands/InGoodHands.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/LostFound/LostFound.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/Own/Own.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/Sell/Sell.jsx
  frontend/src/redux/services/baseApi.js
Labels: bug, fixed

#200 Niko Close #195
  backend/controllers/notices/getFavorites.js
  backend/controllers/notices/getPersonalNotices.js
  frontend/src/App.js
  frontend/src/components/PetPage/NoticesCategoriesNav/Category/Category.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/Category/index.js
  frontend/src/components/PetPage/NoticesCategoriesNav/Favorite/Favorite.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/InGoodHands/InGoodHands.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/InGoodHands/index.js
  frontend/src/components/PetPage/NoticesCategoriesNav/LostFound/LostFound.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/LostFound/index.js
  frontend/src/components/PetPage/NoticesCategoriesNav/NoticesCategoriesNav.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/Own/Own.jsx
  frontend/src/components/PetPage/NoticesCategoriesNav/Sell/index.js
  frontend/src/helpers/lazyRoutes.js
  frontend/src/redux/services/baseApi.js
  frontend/src/redux/services/noticesSlice.js
Labels: enhancement

#207 Niko Close #206
  frontend/src/components/PetPage/ModalNotice/ModalNotice.jsx
  frontend/src/components/PetPage/ModalNotice/ModalNotice.module.scss
  frontend/src/components/PetPage/NoticeCategoryItem/NoticeCategoryItem.jsx
  frontend/src/components/PetPage/NoticeCategoryItem/NoticeCategoryItem.module.scss
  frontend/src/components/PetPage/NoticeCategoryItem/Svg/_like.svg
  frontend/src/images/like-accent.svg
  frontend/src/images/like.svg
  frontend/src/images/remove.svg
  frontend/src/redux/services/baseApi.js
  frontend/src/scss/base/_common.scss
  package-lock.json
Labels: fixed

#210 remake addNotice modal and delete scroll when modal open Close #208 #209
  frontend/src/components/Location/Location.module.scss
  frontend/src/components/ModalAddNotice/ModalAddNotice.jsx
  frontend/src/components/ModalAddNotice/modalAddNotice.module.scss
  frontend/src/components/PetPage/NoticeCategoryItem/NoticeCategoryItem.jsx
  frontend/src/hooks/useModal.js
Labels: fixed

#218 Niko Close #203 #216 #217
  frontend/src/components/AuthNav/AuthNav.module.scss
  frontend/src/components/Header/Header.module.scss
  frontend/src/components/Logo/Logo.module.scss
  frontend/src/components/Nav/Nav.module.scss
  frontend/src/components/Navigation/Navigation.module.scss
  frontend/src/components/PetPage/NoticesSearch/NoticesSearch.jsx
  frontend/src/components/PetPage/NoticesSearch/NoticesSearch.module.scss
  frontend/src/components/PetPage/NoticesSearch/index.js
  frontend/src/components/SearchBox/SearchBox.jsx
  frontend/src/components/SearchBox/index.js
  frontend/src/components/SearchForm/SearchForm.jsx
  frontend/src/components/SearchForm/SearchForm.module.scss
  frontend/src/components/SearchForm/index.js
  frontend/src/components/UserNav/UserNav.module.scss
  frontend/src/images/home/home-desc.svg
  frontend/src/images/home/home.svg
  frontend/src/images/loup.svg
  frontend/src/pages/HomePage/HomePage.module.scss
  frontend/src/pages/NewsPage/NewsPage.jsx
  frontend/src/pages/NewsPage/NewsPage.module.scss
  frontend/src/pages/NoticesPage/NoticesPage.jsx
  frontend/src/pages/NoticesPage/NoticesPage.module.scss
  frontend/src/scss/base/_container.scss
Labels: fixed

#220 Remake AddPetModal Close #219
  frontend/src/components/ModalAddPet/modalAddPet.module.scss
Labels: fixed

#223 Niko Close #228
  frontend/src/components/ModalAddPet/modalAddPet.module.scss
  frontend/src/pages/HomePage/HomePage.jsx
  frontend/src/pages/HomePage/HomePage.module.scss
  frontend/src/scss/base/_container.scss
Labels: fixed
